# These are supported funding model platforms (https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button)

# GitHub Sponsors username (organization or user)
github: [tensilestream]

# Supported alternative developer sponsorship platforms:
# patreon: your_patreon_username
# open_collective: buildanchor
ko_fi: tensilestream
# polar: tensilestream
# buy_me_a_coffee: your_username
# custom: ['https://tensilestream.com/sponsor']
